### ISSUE TITLE
What is the license used?

### ISSUE THREAD

**Issue by paidlowered** [Yasu3D/SlimeX-FDM#1]

**Comment by Yasu3D** [comment]
I haven't put proper thought into that / bothered writing my own license.

I suppose the best fitting license would be CC-BY-NC-SA.

TL;DR of what I'm expecting:
- Provide credit when sharing (link to this repository is fine)
- Only for Non-Commercial use, **unless you have my explicit permission**.
  - You cannot sell the 3d *model*.
  - You cannot sell 3d *prints*.
  - You cannot sell trackers made with this case.
- Any derivative works must follow this license as well.

It's also encouraged to contribute directly to this project and not create "new" versions of it. If you improve the design and want to share it, open a pull request.
